# 1. Numpy 기초

* 라이브러리 임포트

In [1]:
import numpy as np

* Array 정의 및 사용하기

In [2]:
data1= [1,2,3,4,5,6]
data1

[1, 2, 3, 4, 5, 6]

In [3]:
type(data1)

list

In [4]:
data2 = [10,9.9, 9.5, 10, 7.2, 8.0]
data2

[10, 9.9, 9.5, 10, 7.2, 8.0]

#### np는 행렬(array) 아닌가요?
numpy를 array로 정의하기
위에서 만든 list를 이용

In [5]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
arr2 = np.array(data2)
arr2

array([10. ,  9.9,  9.5, 10. ,  7.2,  8. ])

In [7]:
type(arr1)

numpy.ndarray

* array의 크기를 확인 하기

In [8]:
arr1.shape

(6,)

* numpy 함수 알아보기  
zeros(), ones(), arange()

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

* Array 연산

In [13]:
arr1 + arr2

array([11. , 11.9, 12.5, 14. , 12.2, 14. ])

In [14]:
arr1 * arr2

array([10. , 19.8, 28.5, 40. , 36. , 48. ])

In [15]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [16]:
arr2 - arr1

array([9. , 7.9, 6.5, 6. , 2.2, 2. ])

In [17]:
arr2 / arr1

array([10.        ,  4.95      ,  3.16666667,  2.5       ,  1.44      ,
        1.33333333])

In [18]:
arr1 ** 2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

* Type 변경

In [19]:
arr1.dtype

dtype('int32')

In [20]:
f_arr1 = arr1.astype(np.float64)

In [21]:
f_arr1.dtype

dtype('float64')

* Array 인덱싱

In [22]:
# arr1의 4번째 수
arr1[3]

4

In [23]:
# 2번째 부터 5번째 까지
arr1[1:5]

array([2, 3, 4, 5])

In [24]:
data3 = [[1,2,3,4], [5,6,7,8],[9,10,11,12]]
data3

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [25]:
type(data3)

list

In [26]:
arr3 = np.array(data3)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# 3행 2번째 요소 (0부터 count)
arr3[2,1]

10

In [28]:
# 모든 열의 3번째 수
arr3[:,2]

array([ 3,  7, 11])

* Array 마스크  
Array중 원하는 행 또는 열값 뽑아내기

In [29]:
names = np.array(['pyo','sunny','sunyoung','pyo','sunny','sunyoung','psy'])
data = np.random.randn(7,4) 

In [30]:
names

array(['pyo', 'sunny', 'sunyoung', 'pyo', 'sunny', 'sunyoung', 'psy'],
      dtype='<U8')

In [31]:
data

array([[-0.37948004, -0.17332834,  0.8926493 , -0.06299209],
       [ 1.76799426,  0.78594623,  0.54860018, -1.94614774],
       [-1.82128122, -1.8465456 , -0.32029535, -0.33863515],
       [-1.07953192, -0.86163503,  1.41505169,  0.69274224],
       [ 1.24765026, -1.72367289,  0.71512572,  0.91057237],
       [ 0.55269358, -2.02758968,  1.17749745,  1.50516138],
       [-1.11596291,  1.33331746, -0.11179611,  0.95232196]])

In [32]:
names == 'sunyoung'

array([False, False,  True, False, False,  True, False])

In [33]:
data[names == 'sunyoung' , : ]

array([[-1.82128122, -1.8465456 , -0.32029535, -0.33863515],
       [ 0.55269358, -2.02758968,  1.17749745,  1.50516138]])

data 배열 중 행값이 *sunyoung* 인 행의 Data만을 보고 싶을 경우,  
위와 같이 3, 6 행의 값만을 추출해줌.
논리 연산자 처람 *sunyoung* 또는 *sunny*인 행 데이터 꺼내기

In [34]:
data[(names=='sunyoung')|(names=='sunny') ]

array([[ 1.76799426,  0.78594623,  0.54860018, -1.94614774],
       [-1.82128122, -1.8465456 , -0.32029535, -0.33863515],
       [ 1.24765026, -1.72367289,  0.71512572,  0.91057237],
       [ 0.55269358, -2.02758968,  1.17749745,  1.50516138]])

* 마스크를 통한 행열 검색 및 변환

In [35]:
# data array 중 4번째 column값 만 추출
data[ : , 3]

array([-0.06299209, -1.94614774, -0.33863515,  0.69274224,  0.91057237,
        1.50516138,  0.95232196])

In [36]:
# 4열의 값이 0보다 작은 경우
data[ : , 3] < 0 

array([ True,  True,  True, False, False, False, False])

In [37]:
data

array([[-0.37948004, -0.17332834,  0.8926493 , -0.06299209],
       [ 1.76799426,  0.78594623,  0.54860018, -1.94614774],
       [-1.82128122, -1.8465456 , -0.32029535, -0.33863515],
       [-1.07953192, -0.86163503,  1.41505169,  0.69274224],
       [ 1.24765026, -1.72367289,  0.71512572,  0.91057237],
       [ 0.55269358, -2.02758968,  1.17749745,  1.50516138],
       [-1.11596291,  1.33331746, -0.11179611,  0.95232196]])

In [38]:
# 4열의 값이 0보다 작은 경우, 0으로 치환
data[ data[ : , 3] < 0 , : ] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.07953192, -0.86163503,  1.41505169,  0.69274224],
       [ 1.24765026, -1.72367289,  0.71512572,  0.91057237],
       [ 0.55269358, -2.02758968,  1.17749745,  1.50516138],
       [-1.11596291,  1.33331746, -0.11179611,  0.95232196]])

* 행렬 Merge

In [39]:
a = [1,3,5,7,9]
b = [2,4,6,8,10] 
print(a+b)

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]


In [40]:
c = np.array(a)
d = np.array(b)
print(c+d)

[ 3  7 11 15 19]


In [41]:
print(sum(c+d))

55


* 행렬의 정렬(sort)

In [42]:
e = a+b
e

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

In [43]:
# 오름차순 정렬
np.sort(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# 내림 차순 정렬
np.sort(e)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [45]:
# 다차원 배열 정렬 (행별 정렬)
np.sort(data)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.07953192, -0.86163503,  0.69274224,  1.41505169],
       [-1.72367289,  0.71512572,  0.91057237,  1.24765026],
       [-2.02758968,  0.55269358,  1.17749745,  1.50516138],
       [-1.11596291, -0.11179611,  0.95232196,  1.33331746]])